name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"

      - run: npm add -g @antfu/ni
      - run: nci

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          skip-deps: false
          skip-bundle: false
          skip-upload: false
          skip-deploy: true
          skip-release: true
          skip-readme: true
          bundle-command: nr bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
