name: upload-to-test-store

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip actions]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Initialize
        run: make github-init

      - run: npm add -g @antfu/ni
      - run: nci

      - name: Upload NFT Studio Docs to Test Store
        uses: blocklet/action-workflow@v1
        with:
          skip-deps: true
          skip-upload: false
          skip-deploy: true
          skip-release: true
          bundle-command: yarn bundle
          working-directory: website/docs
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

      - name: Upload NFT Studio to Test Store
        uses: blocklet/action-workflow@v1
        with:
          skip-deps: true
          skip-upload: false
          skip-deploy: true
          skip-release: true
          bundle-command: yarn bundle
          working-directory: website/pages
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
